<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CustomLogonUI.cs" />
    <Compile Remove="installer.cs" />
    <EmbeddedResource Include="glitch_effect.gif" LogicalName="glitch_effect.gif" />
  </ItemGroup>
</Project>
