<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="glitch_effect.gif" />
  </ItemGroup>
</Project>
