<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <!-- НИЧЕГО НЕ ДОБАВЛЯЙ СЮДА! SDK ВСЁ СДЕЛАЕТ САМ -->
</Project>
