<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <!-- Добавляем ресурсы -->
    <EmbeddedResource Include="Properties\Resources.resx" />
    <!-- GIF не нужен отдельно, он уже в ресурсах -->
  </ItemGroup>
</Project>
