name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Build CustomLogonUI
      run: |
        dotnet restore CustomLogonUI.csproj
        dotnet build CustomLogonUI.csproj -c Release
        copy CustomLogonUI\bin\Release\net48\CustomLogonUI.exe LogonUI.exe
    - name: Build Installer
      run: |
        dotnet restore LogonUIInstaller.csproj
        dotnet build LogonUIInstaller.csproj -c Release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: payload
        path: LogonUIInstaller\bin\Release\net48\LogonUIInstaller.exe
