name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Restore NuGet packages
      run: |
        nuget restore CustomLogonUI.csproj
        nuget restore LogonUIInstaller.csproj
    - name: Build CustomLogonUI
      run: |
        msbuild CustomLogonUI.csproj /p:Configuration=Release /p:Platform="Any CPU"
        copy CustomLogonUI\bin\Any CPU\Release\net48\CustomLogonUI.exe LogonUI.exe
    - name: Build Installer
      run: msbuild LogonUIInstaller.csproj /p:Configuration=Release /p:Platform="Any CPU"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: payload
        path: LogonUIInstaller\bin\Any CPU\Release\net48\LogonUIInstaller.exe
